Optionally set github personal access token in plugin config
lodi-g/strapi-plugin-github-actions pull request #1
Opened 2021-04-01 16:08 UTC by ggirodda

Hi, thank you for the strapi plugin, it is really useful if we don't want to trigger the github action for every change, when uising web hooks.
I made same changes
- POST method instead of GET for triggering route, considering that there'll be an axios post call to github, that seemed to me more appropriate
- update the axios version, because of the npm critical alert
- added the possibility to set the personal access token using plugin config, if someone doesn't want his / her token to be visible / editable from the workflow form

I added also some test on the added code.

Thanks !

PS. II think that you should set at least the link to github repository and your github ussername in package.json, because there's no information for now on npm weebsite about the package

2021-04-02 08:45 UTC, lodi-g requested changes
Thank you for the quality addition! I have just left 2 comments if you can address them before I merge that'd be great.
I'll also add the repo information for the next release, thanks for the heads up.

2021-04-02 08:45 UTC, lodi-g commented on README.md
> +![Alt text](/strapi-workflow-example.png?raw=true "Strapi Workflow example")
Could you please move the image to a docs folder?

2021-04-02 08:45 UTC, lodi-g commented on services/github-actions.js
> +    if (wfConfigPat) {
Could you log some warning if hasEnvPat is set to true but `config.pats[workflow.name]` doesn't exist. That way we can warn about typos in the config file.

2021-04-05 16:12 UTC, lodi-g commented
Merging in #2 with requested changes

2021-04-05 16:12 UTC, closed without merging

2021-04-05 16:26 UTC, lodi-g commented
Published on npm with version 0.1.0

2021-04-06 22:25 UTC, ggirodda commented
Great, thank you! Sorry for the late reply